export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const USERINFO_SUCCESS = 'USERINFO_SUCCESS';
export const USERINFO_FAIL = 'USERINFO_FAIL';
export const USERINFO_TAB_CHANGE = 'USERINFO_TAB_CHANGE';

export const ISSUER_SUCCESS = 'ISSUER_SUCCESS';
export const ISSUER_FAIL = 'ISSUER_FAIL';

export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const REQUEST_TAB_CHANGE = 'REQUEST_TAB_CHANGE';

export const ADD_ALERT = 'ADD_ALERT';
export const RESET_ALERT = 'RESET_ALERT';
